// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttittypaknnjhtnsyqmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0aXR0eXBha25uamh0bnN5cW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzM3NjUsImV4cCI6MjA1NzkwOTc2NX0.lbXHDBEtEgYmz6AGrSaR5DwKtP0UiqJtqDI_XovLoIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);